package com.tut2.group3.warehouse.utils;

import com.auth0.jwt.JWT;
import com.auth0.jwt.algorithms.Algorithm;
import com.auth0.jwt.exceptions.JWTVerificationException;
import com.auth0.jwt.interfaces.DecodedJWT;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

/**
 * JWT Utility - Compatible with Store Service JWT implementation
 * Uses the same secret and algorithm to verify tokens generated by Store Service
 */
@Component
public class JWTUtil {

    private final String secret;
    private final int expireHours;

    public JWTUtil(@Value("${jwt.secret}") String secret,
                   @Value("${jwt.expire-hours}") int expireHours) {
        this.secret = secret;
        this.expireHours = expireHours;
    }

    /**
     * Parse and verify JWT token
     * Compatible with tokens generated by Store Service
     */
    public DecodedJWT parseToken(String token) throws JWTVerificationException {
        return JWT.require(Algorithm.HMAC256(secret))
                .build()
                .verify(token);
    }

    /**
     * Safe parse token - returns null instead of throwing exception
     */
    public DecodedJWT safeParseToken(String token) {
        try {
            return parseToken(token);
        } catch (Exception e) {
            return null;
        }
    }

    /**
     * Verify token - compatible with Store Service tokens
     */
    public DecodedJWT verifyToken(String token) {
        return parseToken(token);
    }

    /**
     * Extract username from token
     * Store Service uses "username" claim
     */
    public String getUsernameFromToken(String token) {
        DecodedJWT jwt = parseToken(token);
        return jwt.getClaim("username").asString();
    }

    /**
     * Extract user ID from token
     * Store Service uses "userId" claim
     */
    public Long getUserIdFromToken(String token) {
        DecodedJWT jwt = parseToken(token);
        return jwt.getClaim("userId").asLong();
    }

    /**
     * Check if token is valid
     */
    public boolean validateToken(String token) {
        try {
            parseToken(token);
            return true;
        } catch (Exception e) {
            return false;
        }
    }
}
